version: "3"
services:
  frontend:
    build:
      context: ./frontend
    image: frontend:1.0
    ports:
      - 8080:80
    
  backend:
    build:
      context: ./backend
    image: backend:1.0
    ports:
      - 3000:3000